Added Heroku QA link
ucsb-cs156-s22/s22-5pm-courses pull request #12
Opened 2022-05-24 21:55 UTC by anouki-p

Added Heroku QA link to the readme 
Closes issue #5

2022-05-25 23:38 UTC, bzamora020 submitted a review, later dismissed
We need to add the staff to the Heroku Dashboard. Besides that, LGTM!

2022-05-26 00:09 UTC, jaoviedo approved these changes, later dismissed
Staff emails have been properly added to the Heroku dashboard

2022-05-26 00:09 UTC, liminding-UCSB approved these changes, later dismissed
LGTM

2022-05-26 00:37 UTC, andrewpengucsb requested changes, later dismissed

2022-05-26 00:37 UTC, andrewpengucsb commented on README.md
> +
Please add link to qa dashboard!

2022-05-26 21:15 UTC, andrewpengucsb approved these changes
LGTM!

2022-05-26 21:24 UTC, jaoviedo approved these changes
LGTM

2022-05-26 21:28 UTC, andrewpengucsb commented
Going to merge when the checks pass, but make sure you get the app running on the qa deployment as well as oauth, thanks!

2022-05-26 21:30 UTC, merged