5pm 2 api add course limin ding
ucsb-cs156-s22/s22-5pm-courses pull request #34
Opened 2022-05-30 21:24 UTC by liminding-UCSB

In this PR,

1. Add post for CoursesAdded
2. Add tests for post for CoursesAdded

2022-05-30 23:04 UTC, hyunkyumkim approved these changes, later dismissed
LGTM

2022-06-02 05:52 UTC, jacksonjude approved these changes, later dismissed
LGTM

2022-06-02 07:15 UTC, ryanlavu submitted a review, later dismissed
LGTM

2022-06-02 07:45 UTC, hyunkyumkim submitted a review, later dismissed
LGTM

2022-06-03 02:29 UTC, jacksonjude submitted a review, later dismissed
LGTM

2022-06-03 02:31 UTC, ryanlavu approved these changes, later dismissed
LGTM

2022-06-03 07:34 UTC, hyunkyumkim approved these changes, later dismissed
LGTM

2022-06-03 23:54 UTC, pconrad approved these changes
LGTM!  Will test on QA

2022-06-04 00:02 UTC, pconrad requested changes, later dismissed
One small nitpick about the english grammar :-)

2022-06-04 00:02 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/AddedCoursesController.java
> +                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "The enrollCd is not exist in the given quarter");
It would be better if this said 

"The enrollCd does not exist in the given quarter"

That's just better english.

2022-06-04 00:22 UTC, jacksonjude approved these changes, later dismissed
LGTM

2022-06-04 01:17 UTC, hyunkyumkim submitted a review, later dismissed
LGTM

2022-06-04 05:04 UTC, ryanlavu approved these changes, later dismissed
LGTM

2022-06-05 00:06 UTC, pconrad approved these changes, later dismissed
LGTM!

2022-06-05 04:42 UTC, pconrad approved these changes
LGTM

2022-06-05 04:42 UTC, merged